/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const GameType = IDL.Variant({
  'blackjack' : IDL.Null,
  'slots' : IDL.Null,
  'roulette' : IDL.Null,
});
export const GameResult = IDL.Record({
  'timestamp' : Time,
  'gameType' : GameType,
  'amount' : IDL.Nat,
  'outcome' : IDL.Variant({
    'tie' : IDL.Null,
    'win' : IDL.Null,
    'loss' : IDL.Null,
  }),
});
export const Chips = IDL.Nat;
export const CasinoPlayerProfile = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'gameHistory' : IDL.Vec(GameResult),
  'chipBalance' : Chips,
  'totalWinnings' : Chips,
  'lastBonusClaim' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyBonus' : IDL.Func([], [IDL.Nat], []),
  'clearPlayerHistory' : IDL.Func([IDL.Principal], [], []),
  'getCallerChipBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(CasinoPlayerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastGameResults' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getPlayerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CasinoPlayerProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetPlayerBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spinWheel' : IDL.Func([], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const GameType = IDL.Variant({
    'blackjack' : IDL.Null,
    'slots' : IDL.Null,
    'roulette' : IDL.Null,
  });
  const GameResult = IDL.Record({
    'timestamp' : Time,
    'gameType' : GameType,
    'amount' : IDL.Nat,
    'outcome' : IDL.Variant({
      'tie' : IDL.Null,
      'win' : IDL.Null,
      'loss' : IDL.Null,
    }),
  });
  const Chips = IDL.Nat;
  const CasinoPlayerProfile = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'gameHistory' : IDL.Vec(GameResult),
    'chipBalance' : Chips,
    'totalWinnings' : Chips,
    'lastBonusClaim' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyBonus' : IDL.Func([], [IDL.Nat], []),
    'clearPlayerHistory' : IDL.Func([IDL.Principal], [], []),
    'getCallerChipBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerProfile' : IDL.Func(
        [],
        [IDL.Opt(CasinoPlayerProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastGameResults' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getPlayerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CasinoPlayerProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetPlayerBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spinWheel' : IDL.Func([], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };